#!/bin/bash
# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

# Sets the virtual keyboard layout to the right value so that the on screen
# keyboard and KeePassX work correctly.

#setxkbmap de nodeadkeys
#setxkbmap -layout us -variant intl-unicode -option compose:menu,ctrl:nocaps
setxkbmap -layout us -variant altgr-intl -option compose:menu,ctrl:nocaps

xmodmap ~/.xmodmaprc

xbindkeys

logger -t martin-ueding-systemsettings 'mu-keyset done'
