#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

set -u

# ``xinput`` names for the devices.
logitech="Logitech USB Optical Mouse"
mighty="herbertuedings Maus"
point="TPPS/2 IBM TrackPoint"
razer="Razer Razer Diamondback 3G"
touchpad="SynPS/2 Synaptics TouchPad"

xinput --set-ptr-feedback "$logitech" 4 14 10
xinput --set-ptr-feedback "$mighty" 3 30 10
xinput --set-ptr-feedback "$point" 2 35 10
xinput --set-ptr-feedback "$razer" 4 14 10

exit 0
