#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

xrandr --dpi 96

think-dock
think-rotate normal

if type kdialog &> /dev/null
then
    kdialog --title martin-ueding-systemsettings --passivepopup $"mu-startup done"
fi

mu-wakeup
