#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

think-dock
think-rotate normal

think-touchpad

if type kdialog &> /dev/null
then
	#kdialog --title "think-rotate" --passivepopup "Ausführung von think-rotate and think-dock fertig." 1
fi
